.TH "moontop" "1"  "Monday 21 july 2014" "version 1"
.SH NAME
moontop - objectivemoon.io project data collector statistic
.SH SYNOPSIS
.B moontop

.SH DESCRIPTION

.B moontop
This program is part of the objectivemoon.io software suite. The prupose is to give
statistics about
.B mooner
utilisation.

.SH OPTIONS

no option

.SH BUGS 

no well none bug

.SH AUTHOR

mooner@objectivemoon.io

.SH SEE ALSO

www.objectivemoon.io

.SH EXAMPLE 

.B moontop
