.TH "moonpasswd" "1"  "Monday 14 july 2014" "version 1"
.SH NAME
moonpasswd - objectivemoon.io project, print randomize list of 16 character
.SH SYNOPSIS
.B moonpasswd

.SH DESCRIPTION

.B moonpasswd 
generate and print a list of 16 randomize character that can be use as password.

Character are all printable and follow the regexp :
.I [a-z][A-Z][0-1]

.SH OPTIONS

no option

.SH BUGS 

no bug

.SH AUTHOR

mooner@objectivemoon.io

.SH SEE ALSO

www.objectivemoon.io, mooner

